### ISSUE TITLE
Compile failed in old windows SDK

### ISSUE THREAD

**Issue by BlurryLight** [NVIDIAGameWorks/ShaderMake#2]
Information:
Win10 Version: 22H2
Win10 SDK: 10.0.19041.0

Problem:
`ShaderMake` searches DXC in windows sdk directories, but the dxc in sdk is rather old.
The old  `dxcapi.h`  has no definitions about:
- Macros such as `D3DCOMPILE_OPTIMIZATION_LEVEL3`
- Interfaces such as  `IDxcCompiler3`

I have a newer version of DXC bundled with LunarG Vulkan SDK.
To avoid build failures, I have to write lines of hardcoded code about `target_link_libraries/target_include_directories` in cmake files, and copy/paste `dxcompiler.dll` into the binary folder.

Desired Behavoir: 
- `ShaderMake` searches headers and libraries, links from `${ENV:DXC_ROOT}` if exists, instead from windows SDK

**Comment by JakubChomicz** [comment]
What exactly did you change to make it build?

**Comment by BlurryLight** [comment]
```diff
diff --git forkSrcPrefix/CMakeLists.txt forkDstPrefix/CMakeLists.txt
index 1ddf5ea143576654359d0435a35c8d143c7a6eea..0d461ff2f56e4014b5778a198563b2fcac3fafe9 100644
--- forkSrcPrefix/CMakeLists.txt
+++ forkDstPrefix/CMakeLists.txt
@@ -60,10 +60,17 @@ set_property (DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT
 set_property (TARGET ShaderMake PROPERTY FOLDER ShaderMake)
 target_link_libraries (ShaderMake ShaderMakeBlob)
 
+find_package(Vulkan)
+
 if (MSVC)
     target_compile_definitions (ShaderMake PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
     target_link_options (ShaderMake PRIVATE "/DELAYLOAD:dxcompiler.dll")
     target_link_libraries (ShaderMake d3dcompiler dxcompiler delayimp)
+    if(Vulkan_FOUND)
+        message("Vulkan Include Dirs: ${Vulkan_INCLUDE_DIRS}")
+        target_include_directories(ShaderMake BEFORE PRIVATE ${Vulkan_INCLUDE_DIRS}/dxc)
+        target_link_directories(ShaderMake BEFORE PRIVATE ${Vulkan_INCLUDE_DIRS}/../lib)
+    endif()
 else ()
     target_link_libraries (ShaderMake stdc++fs pthread)
 endif ()
```

Simply link dxc in `VulkanSDK` instead of windows SDK.

**Comment by JakubChomicz** [comment]
Thanks

**Comment by dzhdanNV** [comment]
Good that your issue were resolved. I think the default behavior is valid too. According to our logic, on Windows WIN SDK is The King on the party. We do assume that WIN SDK is always kept in a proper state (not necessarily the latest, but matching the expectations). In my opinion, VK SDK adopts all bugs the latest DXC has... Closing or mot? ;)

**Comment by dzhdanNV** [comment]
Today I bumped into a similar problem: DXC from the latest Win SDK just crashed to compile some shaders with HLSL 2021 enabled. As it turned out, DXC from VK SDK worked fine. There was no a need to modify ShaderMake's CMake file. ShaderMake populates `FXC_PATH`, `DXC_PATH` and `DXC_SPIRV_PATH`: I just started to use `DXC_SPIRV_PATH` on Windows in my project.
